"""added new models

Revision ID: 46803a09e10a
Revises: 
Create Date: 2025-11-26 12:46:24.477217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46803a09e10a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'customers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('phone', sa.String(length=64), nullable=True),
        sa.Column('newsletter', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )

    op.create_table(
        'subscribers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )

    op.create_table(
        'reservations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('time_slot', sa.DateTime(), nullable=False),
        sa.Column('table_number', sa.Integer(), nullable=False),
        sa.Column('guests', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    # NOTE: intentionally NOT dropping existing legacy tables such as 'food', 'inventory', 'person',
    # 'recipe', 'ingredient', or 'user'. Those tables are used elsewhere and must be preserved.
    # If you want to remove them, do so in a carefully reviewed migration that handles dependent
    # foreign keys or drops them with CASCADE after confirming it's safe.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only undo objects created in this migration; do not recreate legacy tables.
    op.drop_table('reservations')
    op.drop_table('subscribers')
    op.drop_table('customers')
    # ### end Alembic commands ###