"""updated tables

Revision ID: ceefa663802d
Revises: 46803a09e10a
Create Date: 2025-12-03 16:06:52.677770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceefa663802d'
down_revision = '46803a09e10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('inventory')
    op.drop_table('person')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('food')
    op.drop_table('recipe')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    op.create_table('recipe',
    sa.Column('recipe_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('recipe_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('total_time', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('serving_size', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('recipe_code', name='recipe_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('food',
    sa.Column('food_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('food_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('calorie_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('food_code', name='food_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('person',
    sa.Column('person_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('person_code', name='person_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('food_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inventory_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('purchased_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_updated_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_updated_by_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_updated_reason', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_recipe_code', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['food_code'], ['food.food_code'], name=op.f('foreign_key_inventory_food_code'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_recipe_code'], ['recipe.recipe_code'], name=op.f('foreign_key_inventory_last_recipe_code'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_updated_by_code'], ['person.person_code'], name=op.f('foreign_key_inventory_last_updated_by_code'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('inventory_id', name=op.f('inventory_pkey'))
    )
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('food_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('unit_quantity', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['food_code'], ['food.food_code'], name=op.f('foreign_key_ingredient_food_code'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_code'], ['recipe.recipe_code'], name=op.f('foreign_key_ingredient_recipe_code'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ingredient_id', name=op.f('ingredient_pkey'))
    )
    # ### end Alembic commands ###
